spring:
  application:
    name: EurekaServerDemo #unique name for the application
server:
  port: 8761
eureka:
  client:
    service-url:
      # It consults with other Eureka servers to sync the service registry. As it is in standalone mode, I am giving the local server address.
      defaultZone: http://localhost:8761/eureka/  
    # prevents itself from acting as a client
    register-with-eureka: false 
    # Does not register itself in the service registry.
    fetch-registry: false